# lancemenet build en mode dev : docker compose -f .\docker-compose.dev.yml build
# lancemenet up en mode dev : docker compose -f .\docker-compose.dev.yml up

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: audit-frontend
    volumes:
      - ./apps/frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: yarn dev -H 0.0.0.0

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: audit-backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - audit-node-new
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AUDIT_NODE_URL=http://audit-node-new:3001
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv6Addresses=true
    networks:
      - mynet6
      - auditwp-dev

  audit-node-new:
    build:
      context: ./apps/audit-node-new
      dockerfile: Dockerfile.dev
    container_name: audit-node-new
    ports:
      - "3001:3001"
    volumes:
      - ./apps/audit-node-new:/app
      - audit_node_modules:/app/node_modules
    networks:
      - auditwp-dev
    # Optional healthcheck to ensure backend waits for node to be ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 5s
      retries: 5

networks:
  auditwp-dev:
    driver: bridge
  mynet6:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:1::/64

volumes:
  frontend_node_modules:
  audit_node_modules:
