audit:
  service:
    base-url: ${AUDIT_NODE_URL:http://localhost:3001}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:lahousseludovic@gmail.com}
    password: ${MAIL_PASSWORD:ijku hawv opwl paqm}  # pas ton mot de passe normal, utiliser mot de passe d'application
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
